# 开发环境配置
springdoc:
  paths-to-match: /api/**
  swagger-ui:
    operations-sorter: alpha
spring:
  mail:
    host: smtp.163.com
    username: xi_shuichen@163.com
    password: CLWGHMIXWYWZATFA
  rabbitmq:
    addresses: localhost
    username: admin
    password: 123456
    virtual-host: /
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bootstudy
  security:
    jwt:
      key: 'qjsxepxjalzi'
      expire: 72
      limit:
        base: 10
        upgrade: 300
        frequency: 30
    filter:
      order: -100
  web:
    verify:
      mail-limit: 60
    flow:
      period: 3
      limit: 50
      block: 30
    cors:
      origin: '*'
      credentials: false
      methods: '*'
  minio:
    endpoint: 'http://localhost:9000'
    username: 'minioadmin'
    password: 'minioadmin'
